/**
 * AI Content Detection Module
 * Detects AI-generated content using advanced LLM analysis
 * Created by Lucas Andre S
 */

import { invokeLLM } from "./_core/llm";

export interface AIDetectionSegment {
  textSegment: string;
  aiProbability: number;
  startPosition: number;
  endPosition: number;
  detectionMethod: string;
  reasoning?: string;
}

export interface AIDetectionResult {
  overallPercentage: number;
  segments: AIDetectionSegment[];
  confidenceScore: number;
  totalSegments: number;
}

/**
 * Analyze text patterns for AI characteristics
 */
function analyzeTextPatterns(text: string): number {
  let aiScore = 0;
  
  // Check for repetitive patterns
  const sentences = text.split(/[.!?]+/);
  const avgSentenceLength = sentences.reduce((sum, s) => sum + s.split(/\s+/).length, 0) / sentences.length;
  
  // AI tends to have very consistent sentence lengths
  if (avgSentenceLength > 15 && avgSentenceLength < 25) {
    aiScore += 0.2;
  }
  
  // Check for common AI phrases
  const aiPhrases = [
    'it is important to note',
    'it should be noted',
    'in conclusion',
    'furthermore',
    'moreover',
    'additionally',
    'consequently',
    'therefore'
  ];
  
  const lowerText = text.toLowerCase();
  const phraseCount = aiPhrases.filter(phrase => lowerText.includes(phrase)).length;
  aiScore += Math.min(phraseCount * 0.1, 0.3);
  
  // Check for lack of personal pronouns (AI often avoids first person)
  const personalPronouns = (text.match(/\b(I|me|my|mine|we|us|our)\b/gi) || []).length;
  const wordCount = text.split(/\s+/).length;
  if (personalPronouns / wordCount < 0.01) {
    aiScore += 0.2;
  }
  
  return Math.min(aiScore, 1);
}

/**
 * Use LLM to detect AI-generated content
 */
async function detectAIWithLLM(text: string): Promise<{ probability: number; reasoning: string }> {
  try {
    const response = await invokeLLM({
      messages: [
        {
          role: "system",
          content: "You are an expert AI content detector. Analyze the given text and determine the probability (0-1) that it was generated by an AI. Consider factors like writing style, consistency, vocabulary, sentence structure, and naturalness. Provide your analysis in JSON format."
        },
        {
          role: "user",
          content: `Analyze this text for AI generation:\n\n${text.substring(0, 2000)}`
        }
      ],
      response_format: {
        type: "json_schema",
        json_schema: {
          name: "ai_detection",
          strict: true,
          schema: {
            type: "object",
            properties: {
              probability: {
                type: "number",
                description: "Probability (0-1) that the text was AI-generated"
              },
              reasoning: {
                type: "string",
                description: "Explanation of the detection"
              }
            },
            required: ["probability", "reasoning"],
            additionalProperties: false
          }
        }
      }
    });

    const content = response.choices[0]?.message?.content;
    const contentStr = typeof content === 'string' ? content : '{}';
    const data = JSON.parse(contentStr);
    
    return {
      probability: Math.min(Math.max(data.probability || 0, 0), 1),
      reasoning: data.reasoning || "No reasoning provided"
    };
  } catch (error) {
    console.error("AI detection with LLM failed:", error);
    return {
      probability: 0,
      reasoning: "Detection failed"
    };
  }
}

/**
 * Analyze perplexity and burstiness of text
 */
function analyzePerplexityBurstiness(text: string): number {
  const sentences = text.split(/[.!?]+/).filter(s => s.trim().length > 0);
  
  if (sentences.length < 2) return 0;
  
  // Calculate sentence length variance (burstiness)
  const lengths = sentences.map(s => s.split(/\s+/).length);
  const avgLength = lengths.reduce((a, b) => a + b, 0) / lengths.length;
  const variance = lengths.reduce((sum, len) => sum + Math.pow(len - avgLength, 2), 0) / lengths.length;
  
  // Low variance suggests AI (AI tends to have consistent sentence lengths)
  const burstinessScore = variance < 20 ? 0.3 : 0;
  
  // Check vocabulary diversity
  const words = text.toLowerCase().split(/\s+/);
  const uniqueWords = new Set(words);
  const diversityRatio = uniqueWords.size / words.length;
  
  // AI often has high vocabulary diversity
  const diversityScore = diversityRatio > 0.6 ? 0.2 : 0;
  
  return Math.min(burstinessScore + diversityScore, 1);
}

/**
 * Main AI detection function
 */
export async function detectAIContent(text: string): Promise<AIDetectionResult> {
  try {
    const segments: AIDetectionSegment[] = [];
    
    // Split text into segments for analysis
    const words = text.split(/\s+/);
    const segmentSize = 300; // words per segment
    
    for (let i = 0; i < words.length; i += segmentSize) {
      const segmentWords = words.slice(i, Math.min(i + segmentSize, words.length));
      const segmentText = segmentWords.join(' ');
      
      // Pattern analysis
      const patternScore = analyzeTextPatterns(segmentText);
      
      // Perplexity/burstiness analysis
      const perplexityScore = analyzePerplexityBurstiness(segmentText);
      
      // LLM-based detection
      const llmResult = await detectAIWithLLM(segmentText);
      
      // Combine scores (weighted average)
      const combinedScore = (
        patternScore * 0.2 +
        perplexityScore * 0.2 +
        llmResult.probability * 0.6
      );
      
      segments.push({
        textSegment: segmentText.substring(0, 200) + '...',
        aiProbability: Math.round(combinedScore * 100) / 100,
        startPosition: i,
        endPosition: Math.min(i + segmentSize, words.length),
        detectionMethod: "Multi-algorithm analysis",
        reasoning: llmResult.reasoning
      });
    }
    
    // Calculate overall percentage
    const totalProbability = segments.reduce((sum, seg) => sum + seg.aiProbability, 0);
    const overallPercentage = segments.length > 0 
      ? (totalProbability / segments.length) * 100 
      : 0;
    
    // Calculate confidence score
    const variance = segments.reduce((sum, seg) => {
      const diff = seg.aiProbability - (totalProbability / segments.length);
      return sum + diff * diff;
    }, 0) / segments.length;
    
    const confidenceScore = Math.max(0, 100 - variance * 100);
    
    return {
      overallPercentage: Math.round(overallPercentage * 100) / 100,
      segments: segments.sort((a, b) => b.aiProbability - a.aiProbability),
      confidenceScore: Math.round(confidenceScore * 100) / 100,
      totalSegments: segments.length
    };
  } catch (error) {
    console.error("AI content detection failed:", error);
    return {
      overallPercentage: 0,
      segments: [],
      confidenceScore: 0,
      totalSegments: 0
    };
  }
}

/**
 * Quick AI detection for short texts
 */
export async function quickAIDetection(text: string): Promise<number> {
  const patternScore = analyzeTextPatterns(text);
  const perplexityScore = analyzePerplexityBurstiness(text);
  const llmResult = await detectAIWithLLM(text);
  
  return (patternScore * 0.2 + perplexityScore * 0.2 + llmResult.probability * 0.6) * 100;
}
